/**
 * proyecto
 * filesManager
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jezielpaladino@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * (tsType: Partial<User>, schemaOptions: { partial: true })
 */
export interface UserPartial { 
    id?: number;
    username?: string;
    password?: string;
}

