/**
 * proyecto
 * filesManager
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: jezielpaladino@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileWithRelations } from './fileWithRelations';


/**
 * (tsType: UserWithRelations, schemaOptions: { includeRelations: true })
 */
export interface UserWithRelations { 
    id?: number;
    username: string;
    password: string;
    files?: Array<FileWithRelations>;
}

